sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
node_js:
  - "6"
  - "4"
install:
  - npm install
  - npm prune
before_script:
  - openssl aes-256-cbc -pass "pass:${FIREBASE_ACCOUNT_PASS}" -in ./test/serviceAccount.json.enc -out ./test/serviceAccount.json -d -a
script:
  - make test-coveralls
